export { user, players } from "@/db/schema/tables/user"
export { tags, status } from "@/db/schema/tables/tags"
export { events, eventsTags } from "@/db/schema/tables/event"
export { teams } from "@/db/schema/tables/teams"
export { purchase } from "@/db/schema/tables/purchase"
export { userRelation, eventsRelation, tagsRelation, statusRelation, teamsRelation, playersRelation, eventsTagRelation } from "@/db/schema/relations"
